const Jogos = [

{ 
    "id":1,
    "Nome": "UNCHARTED Legacy of Thieves Collection",
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/uncharted-legacy-of-thieves-collection-torrent.jpg",
    "Imagem": "https://s2.glbimg.com/9l-Q3Wm8Ko3IUsu6YBvSZW9-CBQ=/0x0:695x390/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/Y/Q/JgQUjFSkWkOIus2Ztlbg/uncharted-legacy-thieves-collection-legado-ladroes-colecao-4-nathan.jpg",
    "Gif": "https://thumbs.gfycat.com/VacantLateHoverfly-max-1mb.gif",
    "Trailer": "https://www.youtube.com/embed/xeMA3O9pfiY",
    "Download": "magnet:?xt=urn:btih:8c379ef5a2202e4e838b83cb7509251baaf42dbf&dn=Uncharted.4.Legacy.of.Thieves.Collection.elamigos-games.com",
    "Descricao": `Continue seu legado e deixe sua marca em UNCHARTED: Legacy of Thieves. Experimente a narrativa cinematográfica imersiva da Naughty Dog e as maiores cenas de ação desta série icônica. 
    Explore o passado perdido com os carismáticos e sofisticados ladrões Nathan Drake e Chloe Frazer enquanto viajam pelo mundo em busca de aventuras extraordinárias e histórias esquecidas. 
    UNCHARTED: Legacy of Thieves Collection apresenta as aclamadas aventuras para um jogador de UNCHARTED™ 
    : A Thief's End e UNCHARTED™: The Lost Legacy, remasterizado para o console PS5™ com detalhes impressionantes, gráficos e taxas de quadros aprimorados.
    `,
    "cpu": "Intel i5-4330, AMD Ryzen 3 1200.",
    "gpu": "NVIDIA GTX 960 (4 GB), AMD R9 290X (4 GB)",
    "ram": "8 GB",
    "rom": "126 GB de espaço disponível.",
    "Plataforma": "pc",
    "Tipo": "jogo",
},
{ 
    "id":2,
    "Nome": "Marvels Spider Man Remastered",
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/marvels-spider-man-remastered-torrent.jpg",
    "Imagem":"https://s2.glbimg.com/caiQs82kWLCGmAOCoF-tnmhe5ew=/0x0:1200x675/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2022/O/w/y3y0AFT5mIoCARudZn0g/marvels-spider-man-remastered-pc-segundo-lancamento-sony-pc-god-of-war.jpg",
    "Gif":"https://thumbs.gfycat.com/FriendlySimpleDogwoodclubgall-size_restricted.gif",
    "Trailer": "https://www.youtube.com/embed/SQjA1-vpd0E",
    "Download": "magnet:?xt=urn:btih:68a1f81de513e36386821708a0844c00e91b0207&dn=Marvels_Spider-Man_Remastered-FLT&tr=http%3a%2f%2ftracker.trackerfix.com%3a80%2fannounce&tr=udp%3a%2f%2f9.rarbg.me%3a2960%2fannounce&tr=udp%3a%2f%2f9.rarbg.to%3a2910%2fannounce&tr=udp%3a%2f%2ftracker.thinelephant.org%3a12770%2fannounce&tr=udp%3a%2f%2ftracker.fatkhoala.org%3a13760%2fannounce",
    "Descricao":`Sentindo-se como o Homem-Aranha 
    Com oito anos de experiência por trás da máscara, Peter Parker é um especialista no combate ao crime. Ele sente todo o poder do mais experiente Homem-Aranha e aprecia sua capacidade de improvisar em combate, sua agilidade acrobática e a facilidade com que se movimenta pela cidade e interage com o ambiente. 
    Worlds Collide 
    Os mundos de Peter Parker e do Homem-Aranha colidem nesta nova história repleta de ação. Neste novo universo do Homem-Aranha, alguns dos personagens icônicos da vida de Peter e Homem-Aranha foram reimaginados para colocar os personagens que já conhecemos em papéis únicos.
    `,
    "cpu":"Intel Core i3-4160, 3.6 GHz",
    "gpu":"NVIDIA GTX 950 ou AMD Radeon RX 470.",
    "ram":"8 GB",
    "rom":"75 GB",
    "Plataforma":"pc",
    
},
{ 
    "id":3,
    "Nome": "Dying Light 2 Stay Human",
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/dying-light-2-stay-human-gratis-dublado-torrent.jpg",
    "Imagem":"https://i0.wp.com/gamehall.com.br/wp-content/uploads/2021/08/dying-light-2-luta.jpg?resize=780%2C470&ssl=1",
    "Gif":"https://c.tenor.com/rpK6oLT9kfgAAAAd/dying-light2-stay-human.gif",
    "Trailer": "https://www.youtube.com/embed/2MD4gTitmzw",
    "Download": "downloadççç",
    "Descricao":`Lutamos contra o vírus em Harran por mais de vinte anos - e perdemos. Agora estamos perdendo de novo. A cidade, um dos últimos grandes assentamentos humanos, é dilacerada pelo conflito. A civilização retornou à Idade das Trevas. No entanto, temos esperança. 
    Você é um viajante com o poder de mudar o destino de uma cidade. No entanto, suas habilidades extraordinárias têm um preço. Assombrando memórias que você não consegue interpretar, você luta para encontrar a verdade... e entra em uma zona de combate. Aumente suas habilidades porque força e inteligência são necessárias para derrotar os inimigos e fazer aliados. Desafie os segredos sombrios daqueles que estão no poder, escolha seu lado e decida seu próprio destino. Onde quer que suas ações o levem, há uma coisa que você nunca deve esquecer - permaneça humano.
    `,
    "cpu":"AMD Ryzen 5 3600X ou Intel i5-8600K",
    "gpu":"NVIDIA® GeForce RTX™ 2060 6GB ou AMD RX Vega 56 8GB",
    "ram":"16 GB",
    "rom":"60 GB",
    "Plataforma":"pc",
    
},
{ 
    "id":4,
    "Nome": "Stray",
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/stray-torrent.jpg",
    "Imagem":"https://i0.wp.com/gamersmaze.com/wp-content/uploads/2022/08/Stray-Gameplay-Image-3.jpg?fit=1280%2C720&ssl=1",
    "Gif":"https://64.media.tumblr.com/64fba490da542c3f2621c1eec30ebaef/04210af781c40b75-73/s540x810/d43544f7be1230d59ef0e8d276bc76594d56079c.gifv",
    "Trailer": "https://www.youtube.com/embed/b-ugdyfd0ao",
    "Download": "magnet:?xt=urn:btih:68CF60AEA72E0EE8592BD588D86348C204918664&dn=Stray+v1.4.227&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2F47.ip-51-68-199.eu%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2920%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce",
    "Descricao":`Um gato perdido, solitário e ferido deve resolver um mistério antigo para escapar de uma cidade esquecida. 
    Stray é um jogo de aventura de gato em terceira pessoa ambientado nos becos iluminados por neon de uma cidade futurista e nos lugares sombrios de seu submundo. 
    Veja o mundo pelos olhos de um gato de rua e interaja com o ambiente de uma forma divertida. 
    Stray foi desenvolvido pela BlueTwelve Studio, uma pequena equipe no sul da França, composta principalmente por gatos e algumas pessoas.
    `,
    "cpu":"Intel Core i5-2300 | AMD FX-6350.",
    "gpu":"NVIDIA GeForce GTX 650 Ti, 2 GB",
    "ram":"8 GB",
    "rom":"10 GB",
    "Plataforma":"pc",
    
},
{ 
    "id":5,
    "Nome": "God of War",
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/god-of-war-portugues-torrent.jpg",
    "Imagem":"https://s2.glbimg.com/VnoWsL6fvSZPRdJMsy_KIdMsf2s=/0x0:1200x675/540x304/smart/filters:max_age(3600)/https://i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2022/F/8/WrRTVFQgSAkuQ5FtbICw/god-of-war-ragnarok-lojas-venda-antecipada-diretor-cory-balrog-irritado.jpg",
    "Gif":"https://media0.giphy.com/media/l41YfXDjhJypfgD0k/giphy.gif",
    "Trailer": "https://www.youtube.com/embed/jCB36uNrZ9I",
    "Download": "magnet:?xt=urn:btih:4F515CD16844D32DF2AAB1995C2561D759DCEAA6&dn=God+of+War+%282022%29+MULTi19-ElAmigos&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969%2Fannounce&tr=http%3A%2F%2F104.28.1.30%3A8080%2Fannounce&tr=http%3A%2F%2F104.28.16.69%2Fannounce&tr=http%3A%2F%2F107.150.14.110%3A6969%2Fannounce&tr=http%3A%2F%2F109.121.134.121%3A1337%2Fannounce&tr=http%3A%2F%2F114.55.113.60%3A6969%2Fannounce&tr=http%3A%2F%2F125.227.35.196%3A6969%2Fannounce&tr=http%3A%2F%2F128.199.70.66%3A5944%2Fannounce&tr=http%3A%2F%2F157.7.202.64%3A8080%2Fannounce&tr=http%3A%2F%2F158.69.146.212%3A7777%2Fannounce&tr=http%3A%2F%2F173.254.204.71%3A1096%2Fannounce&tr=http%3A%2F%2F178.175.143.27%2Fannounce&tr=http%3A%2F%2F178.33.73.26%3A2710%2Fannounce&tr=http%3A%2F%2F182.176.139.129%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce",
    "Descricao":`Do Santa Monica Studios, é a sequência do aclamado God of War de 2018. O inverno de Vibol começou. Kratos e Atreus devem viajar pelos nove mundos para encontrar respostas enquanto o exército de Asgard se prepara para uma batalha profética que levará ao fim do mundo. Nesta jornada, eles explorarão fantásticas paisagens míticas  e encontrarão inimigos aterrorizantes: deuses  e monstros nórdicos. A ameaça do Ragnarok está se aproximando. Kratos e Atreus terão que escolher entre sua própria segurança e a segurança do mundo.
    `,
    "cpu":"NVIDIA GTX 960 (4GB) ou AMD R9 290X (4GB)",
    "gpu":"Intel i5-2500k (4 core 3.3 GHz)",
    "ram":"8 GB",
    "rom":"80 GB",
    "Plataforma":"pc",
    
},
{ 
    "id":6,
    "Nome": "Far Cry 6 Ultimate Edition",
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/far-cry-6-crack-torrent.jpg",
    "Imagem":"https://store.ubi.com/dw/image/v2/ABBS_PRD/on/demandware.static/-/Sites-masterCatalog/default/dw26c25a30/images/large/5ecd2d445cdf9a1528a8c1d3-5.png?sw=783&sh=440&sm=fit",
    "Gif":"https://geekhere.com.br/wp-content/uploads/2021/10/tumblr_df3b29087bd0ac3dfa8485be74636840_06a30966_500.gif",
    "Trailer": "https://www.youtube.com/embed/-IJuKT1mHO8",
    "Download": "magnet:?xt=urn:btih:192494E9498BF45256E04774B264629856492714&dn=Far+Cry+6+%26ndash%3B+Ultimate+Edition+%28v1.5.0+%2B+All+DLCs+%2B+HD+Texture+Pack+%2B+MULTi15%29+%28From+40.4+GB%29+-+%5BEMPRESS+%2F+DODI+Repack%5D&tr=udp%3A%2F%2F9.rarbg.to%3A2870%2Fannounce&tr=udp%3A%2F%2Feddie4.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fthetracker.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337&tr=udp%3A%2F%2F9.rarbg.com%3A2710%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker1.wasabii.com.tw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.cypherpunks.ru%3A6969%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce",
    "Descricao":`O ditador de Yala Anton Castillo quer que seu filho Diego, tão sanguinário quanto seu pai, salve a glória de seu país a qualquer custo. O governo autoritário de Anton e Diego causou uma revolução. - Jogue como Dani Rojas, filho de Yalani, e junte-se aos combatentes revolucionários de hoje para libertar Yarra!
    `,
    "cpu":"AMD Ryzen 3 1200 3 GHz",
    "gpu":"AMD RX 460 (4 GB)",
    "ram":"8 GB",
    "rom":"60 GB",
    "Plataforma":"pc",
    
},
{ 
    
    "id":8,
    "Nome": "ELDEN RING",
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/elden-ring-completo-torrent.jpg",
    "Imagem":"https://img.olhardigital.com.br/wp-content/uploads/2022/01/elden-ring.png",
    "Gif":"https://media4.giphy.com/media/h9UsipSc6PmbAY1Axi/giphy.gif",
    "Trailer": "https://www.youtube.com/embed/E3Huy2cdih0",
    "Download": "magnet:?xt=urn:btih:DBC18C37C78C85F4CF91C294D2518203864EFF52&dn=ELDEN+RING+v1+04+1-FLT&tr=udp%3A%2F%2F9.rarbg.me%3A2720%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2800%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce",
    "Descricao":`Elden Ring, o novo jogo do diretor de Dark Souls, Bloodborne e Sekiro: Shadows Dies Twice, foi lançado há menos de um mês, mas  se tornou um fenômeno popular. Além de ser um dos jogos mais esperados deste ano, Elden Ring teve um bom desempenho nos sites de análise de jogos Metacritic e OpenCritic. 
    é um RPG de mundo aberto que se passa no meio do mundo depois que o "Elden Ring" é destruído e  seus fragmentos, The Great Runes. Os jogadores devem viajar pelo mundo, encontrar todas as runas capitais, coletar o Elden Ring e se tornar o Elden Master.
   `,
    "cpu":"Intel Core i5-8400 ou AMD Ryzen 3 3300X.",
    "gpu":"Nvidia Geforce GTX 1060 3 GB",
    "ram":"12 GB",
    "rom":"60 GB",
    "Plataforma":"pc",
    
},
{ 
    "id": 9,
    "Nome": "Resident Evil Village", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/resident-evil-village-torrent.jpg", 
    "Imagem": "https://adrenaline.com.br/uploads/chamadas/resident-evil-village-terceira-pessoa_(2).jpg", 
    "Gif": "https://media.tenor.com/Vd9EMA8UcysAAAAd/resident-evil-village-re8.gif", 
    "Trailer": "https://www.youtube.com/embed/Qge5m24C5qs", 
    "Download": "magnet:?xt=urn:btih:7BP2664C2GGCV4NTXPPYN4BB55JZMPAU&dn=Resident%20Evil%20Village%20Deluxe%20Edition%20v2&tr=udp%3A%2F%2Fshubt.net%3A2710", 
    "Descricao": "Neste novo jogo de Resident Evil, os jogadores irão vivenciar uma história com Ethan, o protagonista de RE 7: Resident Evil. Após os acontecimentos do jogo de 2017, o personagem tenta voltar ao normal com a esposa Mia e a filha Rosemary. Mas no início da vila, ele é surpreendido pelo famoso Chris Redfield, que matou Mia e sequestrou Rose.   Ethan, que briga com Chris,  acorda em uma cidade completamente destruída e parece ter um carinho especial  por uma personagem semi-religiosa chamada Mama Miranda. Lá, ele embarca em uma jornada para encontrar Rosemary, enfrentar vários inimigos e descobrir inúmeros segredos.", 
    "cpu": "AMD Ryzen 3 1200", 
    "gpu": "AMD Radeon RX 560 with 4GB VRAM", 
    "ram": "8 GB", 
    "rom": "70 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},

{ 
    "id": 10,
    "Nome": "Days Gone", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/days-gone-torrent.jpg", 
    "Imagem": "https://s2.glbimg.com/vA_kfNPvWtoRVYXlOneovY5F38s=/0x0:1920x1075/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2019/g/C/dLzbSHQheQDUINlgwyfg/80.jpg", 
    "Gif": "https://thumbs.gfycat.com/AdorableDesertedAkitainu-size_restricted.gif", 
    "Trailer": "https://www.youtube.com/embed/qTsx64xYhPM", 
    "Download": "magnet:?xt=urn:btih:50E0E662E8E91221708FCCF077389D0917981C9E&dn=Days+Gone+%28MULTi23%29+%5BFitGirl+Repack%2C+Selective+Download+-+from+20.1+GB%5D&tr=udp%3A%2F%2F46.148.18.250%3A2710&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=http%3A%2F%2Fretracker.local%2Fannounce&tr=http%3A%2F%2Fretracker.ip.ncnet.ru%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce", 
    "Descricao": "Days Gone é um jogo de ação e aventura de mundo aberto ambientado em um ambiente hostil, dois anos após uma pandemia global devastadora. Jogue como Deacon St. Deolate Open World: Usando o poder do PlayStation   e do Unreal Engine  , Days Gone oferece uma experiência de mundo aberto incrivelmente realista e detalhada. Mergulhe em um ambiente vasto e hostil e descubra seus segredos. Procure  veículos abandonados, casas, barracos de beira de estrada e cidades em sua busca por recursos. Mas tenha cuidado:  ciclos diurnos e noturnos e um sistema climático dinâmico podem afetar a jogabilidade e o comportamento do inimigo. Simulação de Combate Brutal: Aprimore seu jogo com uma mistura infinita de estratégia e jogabilidade em qualquer situação. Crie itens personalizados usando itens na natureza, desde armas brutais corpo a corpo até armadilhas; E mais Aja com sabedoria porque qualquer escolha pode significar a diferença entre a vida e a morte. Inimigos únicos: Além de caminhantes humanos, milícias e ladrões, os diáconos devem atravessar um deserto cheio de monstros - criaturas selvagens e irracionais.", 
    "cpu": "ntel Core i5-2500K 3,3 GHz", 
    "gpu": "Nvidia GeForce GTX 780 3GB", 
    "ram": "8 GB", 
    "rom": "70 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},

{ 
    "id": 11,
    "Nome": "Grand Theft Auto V", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/grand-theft-auto-v-torrent.jpg", 
    "Imagem": "https://compass-ssl.xbox.com/assets/a0/4f/a04f2744-74d9-4668-8263-e0261fbea869.jpg?n=GTA-V_GLP-Page-Hero-1084_1920x1080.jpg", 
    "Gif": "https://c.tenor.com/O1xbMwIRJcsAAAAd/grand-theft-auto-grand-theft-auto-v.gif", 
    "Trailer": "https://www.youtube.com/embed/dnSTk7wCtAM", 
    "Download": "magnet:?xt=urn:btih:58a92f8072b724dd34d0d4a5472ec2ea250f27ce&dn=Grand+Theft+Auto+V+v1.50+ElAmigos", 
    "Descricao": "Grand Theft Auto V:  Grand Theft Auto V:  Premium Edition inclui o modo de história completo de Grand Theft Auto V, acesso gratuito ao crescente mundo de Grand Theft Auto Online, todo o conteúdo do jogo e aprimoramentos de lançamento, como The Doomsday Heist, Gunrunning e Above the Certo, motociclistas e muito mais. Você receberá um conjunto de ferramentas de planejamento do crime, que é a maneira mais rápida de iniciar seu império do crime em Grand Theft Auto Online.", 
    "cpu": "Intel Core 2 Quad CPU Q6600 de 2.40GHz", 
    "gpu": "NVIDIA 9800 GT 1GB", 
    "ram": "4 GB ", 
    "rom": "90 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 12,
    "Nome": "Mortal Kombat 11", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/mortal-kombat-11-torrent.jpg", 
    "Imagem": "https://s2.glbimg.com/FvR0RS5wd2ILAvoROYPcA37FJeA=/0x0:768x480/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2020/v/I/OStL4cTZq3bHNhFOITmw/mk11-wbgames.jpg", 
    "Gif": "https://i.pinimg.com/originals/19/56/25/195625f8a6267e32ebe3bfa5a046b3ac.gif", 
    "Trailer": "https://www.youtube.com/embed/H3lfTa3JCek", 
    "Download": "magnet:?xt=urn:btih:5D81D903CDDC963A293FF8E7473F858CD4CE8747&dn=Mortal+Kombat+11+%28v09.29.2020+%2B+All+DLCs%2C+MULTi12%29+%5BFitGirl+Repack%2C+Selective+Download+-+from+52.3+GB%5D&tr=udp%3A%2F%2F46.148.18.250%3A2710&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=http%3A%2F%2Fretracker.local%2Fannounce&tr=http%3A%2F%2Fretracker.ip.ncnet.ru%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce", 
    "Descricao": "Dois anos após os eventos de Mortal Kombat X, Kronika, a Titã do Tempo e mãe do deus de Shinnok, traça um plano para repetir a história com a Ampulheta, um artefato capaz de controlar livremente o tempo, facilitado pelas mudanças causadas por Raiden. ...na timeline, com a mensagem He will win em Mortal Kombat (2011). Para este fim, ele recuperou clones de personagens de Outworld e Earthrealm, e se aliou aos agora caídos Linkui e Shaohan, que são ressuscitados pelo poder de Kronika. Guerreiros do passado e do presente devem se unir para frustrar os planos do vilão.,",
    "cpu": "Intel Core i5-750, 2.66 GHz", 
    "gpu": " NVIDIA® GeForce™ GTX 670", 
    "ram": "8 GB", 
    "rom": "80 Gb", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 13,
    "Nome": "Need for Speed Heat", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/need-for-speed-heat-torrent.jpg", 
    "Imagem": "https://cdn.akamai.steamstatic.com/steam/apps/1281881/ss_6994870577a41882c458cd00d852d8092116c81c.1920x1080.jpg?t=1663269323", 
    "Gif": "https://media.tenor.com/1bwPvQl9ppcAAAAC/need-for-speed-heat-nfs.gif", 
    "Trailer": "https://www.youtube.com/embed/9ewiJJe_nYI", 
    "Download": "magnet:?xt=urn:btih:WYYJHKQQVNK54YJXOVAG5X5GDZZIYCHI&dn=Need%20for%20Speed%20Heat%20MULTI%20V2%20ElAmigos&tr=udp%3A%2F%2Fshubt.net%3A2710", 
    "Descricao": "Need for Speed: Heat é um jogo de corrida de mundo aberto ambientado em uma cidade conhecida como Palm City, uma versão fictícia de Miami, Flórida. [10] Ao contrário de Need for Speed's Revenge, The Heat não tem um ciclo dia-noite de 2  horas, mas os jogadores podem alternar entre dia e noite. Durante o dia, os jogadores podem participar de eventos de corrida puníveis que recompensam os jogadores com dinheiro para comprar novos carros  e atualizações. Eles também podem participar de corridas de rua ilegais à noite, dando aos jogadores um REP. Quanto mais representações ele ganhar, mais agressiva será a polícia à noite, e o jogador terá que fugir da polícia e voltar ao seu esconderijo antes de ser preso ou  seu veículo ser destruído.", 
    "cpu": "(AMD): FX-6350", 
    "gpu": "GeForce GTX 760", 
    "ram": "8 GB", 
    "rom": "50 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 14,
    "Nome": "Cyberpunk 2077", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/cyberpunk-2077-gratis-dublado-torrent.jpg", 
    "Imagem": "https://www.cyberpunk.net/build/images/home3/screen-image-mercenary-e79283ec.jpg", 
    "Gif": "https://media.tenor.com/4Zcc87dUPiMAAAAC/cyberpunk2077-cyberpunk.gif", 
    "Trailer": "https://www.youtube.com/embed/liuFhVXAlZw", 
    "Download": "magnet:?xt=urn:btih:b4204968ebbae3fec2649f3fa43057731f50f261&dn=Cyberpunk.2077.v1.5-CODEX&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2870&tr=udp%3A%2F%2F9.rarbg.to%3A2860&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12770&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15710", 
    "Descricao": "Cyberpunk 2077 é uma história de  aventura em mundo aberto ambientada em Night City, uma cidade obcecada por poder, brilho e arquétipos de criaturas. Você joga como V, um mercenário fora da lei que detém a chave da imortalidade por trás de um implante único.", 
    "cpu": "AMD FX-8310", 
    "gpu": "NVIDIA GeForce GTX 970", 
    "ram": "8 GB", 
    "rom": "70 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 15,
    "Nome": "Dragon Ball Z Kakarot Ultimate Edition", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/dragon-ball-z-kakarot-ultimate-edition-torrent.jpg", 
    "Imagem": "https://static.kinguin.net/cdn-cgi/image/w=1140,q=80,fit=scale-down,f=auto/media/category/s/s/ss_d2ccffa12841ccf7862914d80f38dd609a00ed81.1920x1080_1577703816_2_2_1.jpg", 
    "Gif": "https://media.tenor.com/JZcfGYiualcAAAAC/freiza-goku.gif", 
    "Trailer": "https://www.youtube.com/embed/Bf85wwJuFBE", 
    "Download": "magnet:?xt=urn:btih:985449d8f465bec39f908a998d8de3dccb5c5638&dn=Dragon+Ball+Z+Kakarot+Ultimate+Edition+v1.60", 
    "Descricao": "Experimente a história de DRAGON BALL Z, de eventos épicos a missões secundárias divertidas, incluindo momentos totalmente novos que contam alguns dos fatos revelados pela primeira vez na história de DRAGON BALL!   Jogue o icônico jogo DRAGON BALL Z em uma escala incomparável. Lute em vastos campos de batalha com ambientes destrutíveis e experimente batalhas épicas contra chefes que testarão os limites de suas habilidades de luta. Aumente sua força e aceite o desafio!   Não lute como um lutador Z, viva como eles! Divirta-se caçando, voando, comendo, treinando e lutando em DRAGON BALL Z Saga, fazendo amigos e construindo relacionamentos com muitos personagens.", 
    "cpu": "Intel Core i5-2400", 
    "gpu": "GeForce GTX 750 Ti", 
    "ram": "4 GB", 
    "rom": " 36 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 16,
    "Nome": "Red Dead Redemption 2", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/red-dead-redemption-2-ultimate-edition-torrent.jpg", 
    "Imagem": "https://adrenaline.com.br/uploads/chamadas/Red_Dead_Redemption_2_historia_miss%C3%B5es_modders.jpg", 
    "Gif": "https://media4.giphy.com/media/fjxbfQKLcKzAJIqSuD/giphy.gif", 
    "Trailer": "https://www.youtube.com/embed/WDvFz2LL1WI", 
    "Download": "magnet:?xt=urn:btih:4A00FF80E34B4577ADF34F08D788C83BA7AEFB7A&dn=Red+Dead+Redemption+2%3A+Ultimate+Edition+%5B1.0.1311.23%5D+%28MULTi13%29-InsaneRamZes&tr=http%3A%2F%2Ftr.ysagin.top%3A2710%2Fannounce&tr=http%3A%2F%2Ftr2.ysagin.top%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce", 
    "Descricao": "Red Dead Redemption II é um videogame de ação e aventura desenvolvido pela Rockstar Studios e publicado pela Rockstar Games. É uma prequela de Red Dead Redemption de 2010 e é a terceira entrada da série Red Dead. A trama gira em torno de Arthur Morgan, um dos principais membros da gangue de Van der Linde.   Red Dead Redemption II foi lançado  em 26 de fevereiro de 2019 no PlayStation   e Xbox One, com críticos elogiando sua história de renome mundial e nível de detalhes. O jogo arrecadou US $ 877 milhões  em vendas de fim de semana de abertura e vendeu mais de 67 milhões de cópias em duas semanas.", 
    "cpu": "Intel Core i5-2500K", 
    "gpu": "GeForce GTX 770 2GB", 
    "ram": "8GB", 
    "rom": "150GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 17,
    "Nome": "Biomutant ", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/biomutant-torrent.jpg", 
    "Imagem": "https://sm.ign.com/ign_br/gallery/b/biomutant-/biomutant-screenshots_944e.jpg", 
    "Gif": "https://c.tenor.com/-jVX_NFQNzEAAAAd/biomutant-bio.gif", 
    "Trailer": "https://www.youtube.com/embed/r5c0-TFP18g", 
    "Download": "magnet:?xt=urn:btih:e6cd1358fe51fb2524af475f599aed078e7454da&dn=Biomutant.v1.3-GOG&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2980&tr=udp%3A%2F%2F9.rarbg.to%3A2720&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13770&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12790", 
    "Descricao": "BIOMUTANT® é um incrível RPG  de Kung Fu pós-apocalíptico de mundo aberto com um sistema de combate único no estilo de artes marciais  que permite combinar habilidades corpo a corpo,  tiro e  mutantes. Uma praga devasta a região e a Árvore da Vida sangra pela morte de suas raízes. As tribos estão divididas. Explore um mundo conturbado e decida seu próprio destino: você será o salvador dela ou a levará a um destino ainda mais sombrio? Download do jogo biomutant completo para pc via torrent.", 
    "cpu": "AMD FX-8350 ou Intel Core i5 4690K", 
    "gpu": "GeForce GTX 960", 
    "ram": "8 GB", 
    "rom": "25 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 18,
    "Nome": "Marvels Guardians of the Galaxy", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/marvels-guardians-of-the-galaxy-torrent.jpg", 
    "Imagem": "https://assets-prd.ignimgs.com/2022/02/22/23aaa000-1b24-11ec-b9f8-ed81dceed126-cf-1635612074088-1645554150274.jpeg", 
    "Gif": "https://cdn2.unrealengine.com/1-marvel-guardians-of-the-galaxy-925f24ac69c5.gif", 
    "Trailer": "https://www.youtube.com/embed/NCP9g8cjp-o", 
    "Download": "magnet:?xt=urn:btih:C5301A029BBC3B298E4A36EA4267CE3E2EDAD93A&dn=Marvels.Guardians.of.the.Galaxy-EMPRESS&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2780%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2730%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce", 
    "Descricao": "Embarque em uma nova e emocionante jornada pelo universo em Guardiões da Galáxia Vol. Neste jogo de ação e aventura em terceira pessoa, você joga como Star-Lord que, sob sua liderança ousada e questionável, monta uma equipe excêntrica de heróis improváveis. Alguns idiotas (definitivamente não  você) desencadeiam uma cadeia cataclísmica de eventos, e  você é o único capaz de manter os Guardiões imprevisíveis  por tempo suficiente para evitar o colapso interestelar final. Use armas primárias, ataques em grupo, botas de reação... o que for.   Se você acha que tudo vai correr conforme o planejado,  terá muitas surpresas, pois as consequências de suas ações manterão os guardas em guarda. Nesta história original de Guardiões da Galáxia da Marvel, você conhecerá novas criaturas poderosas e personagens icônicos, todos envolvidos em uma batalha pelo destino da galáxia. É hora de mostrar ao universo do que você é capaz.   Você pode fazer isso. pensar", 
    "cpu": "AMD Ryzen™ 5 1400", 
    "gpu": "AMD Radeon RX 570", 
    "ram": "8 GB", 
    "rom": "150 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 19,
    "Nome": "Watch Dogs Legion", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/watch-dogs-legion-02-torrent.jpg", 
    "Imagem": "https://sm.ign.com/ign_br/screenshot/default/watch-dogs-legion-streetartist-vignettelight_xkyd.png", 
    "Gif": "https://thumbs.gfycat.com/BeneficialForkedKodiakbear-size_restricted.gif", 
    "Trailer": "https://www.youtube.com/embed/VCuEA0pAi-g", 
    "Download": "magnet:?xt=urn:btih:CACAD2258EE507FF2C265DD3D0DB93D8D46F06DF&dn=Watch.Dogs.Legion-EMPRESS&tr=http%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce", 
    "Descricao": "Watch Dogs: Legion é um jogo de ação e aventura em terceira pessoa. O jogo se passa em um mundo aberto e narrativo em Londres, que incluirá os famosos marcos, regiões e padrões culturais da cidade. O  jogo se passa em Londres, que se tornou uma cidade de vigilância em massa. As liberdades pessoais são severamente restringidas e os movimentos dos cidadãos são constantemente monitorados  pela Albion, uma empresa de segurança privada que atua como a polícia da cidade.   Os jogadores poderão explorar rapidamente a  cidade a pé, usando um veículo ou  pelas estações de metrô da cidade. Ao contrário dos jogos anteriores da série, que se concentravam em usar um único herói para liderar a  história, Legion tem a capacidade de controlar vários personagens no jogo.", 
    "cpu": "Intel Core i5-4460", 
    "gpu": "NVIDIA GeForce GTX 960", 
    "ram": "8 GB", 
    "rom": "80 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 21,
    "Nome": "Warcraft III: The Frozen Throne", 
    "Capa": "https://upload.wikimedia.org/wikipedia/en/8/87/Warcraftiii-frozen-throne-boxcover.jpg", 
    "Imagem": "https://img.informer.com/pb/warcraft-iii-frozen-throne-v1.5-warcraft-3-frozen-throne-1.png", 
    "Gif": "https://thumbs.gfycat.com/OptimisticJoyfulAvocet-max-1mb.gif", 
    "Trailer": "https://www.youtube.com/embed/UgTmcnR3iaY", 
    "Download": "https://drive.google.com/file/d/1qmmq81HYS7_UNtQ5dSkgF_Al1c08JGos/view?usp=share_link", 
    "Descricao": "O Warcraft III apresentou uma mudança importante com relação às versões anteriores do jogo: unidades únicas, mais poderosas, chamadas Heroes. Um herói no jogo pode achar ou trocar itens mágicos para melhorar suas características e atributos, ao género dos RPGs. Os heróis podem também adquirir auras de proteção através de habilidades, que beneficiam unidades aliadas que estão próximas dele. Tal como nos RPGs, os heróis ganham experiência através de combate, subindo de nível, e desbloqueando novas habilidades ou melhorando aquelas que já possui.   Outra inovação são os creeps: criaturas controladas pelo computador, presentes mesmo em jogos multijogador. Eles guardam certas áreas do mapa. Estes são usados ​​para aumentar o nível do herói no início do jogo à medida que ele ganha experiência e tesouros.", 
    "cpu": "Intel Core i3-530", 
    "gpu": "AMD Radeon HD 5750", 
    "ram": "4 GB", 
    "rom": "30 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 22,
    "Nome": "The Sims 4 Deluxe Edition", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/the-sims-4-deluxe-edition-torrent.jpg", 
    "Imagem": "https://cdn.cloudflare.steamstatic.com/steam/apps/1235765/ss_6a22fda926a224ed6ff6243f0919c824bf921a71.1920x1080.jpg?t=1666909174", 
    "Gif": "https://cdn.cloudflare.steamstatic.com/steam/apps/1222670/extras/TS4_01_610x343_EN.gif?t=1666819875", 
    "Trailer": "https://www.youtube.com/embed/DL2hlOIf-PM", 
    "Download": "magnet:?xt=urn:btih:dd670edc556b8fb0ce860d66c2e8dd4b7fdf2a8b&dn=The.Sims.4.Digital.Deluxe.Edition.v1.92.145.elamigos-games.com", 
    "Descricao": "The Sims   se concentra na criação de personagens e ferramentas aprimoradas de construção de casas, bem como  uma simulação de jogabilidade mais profunda dos Sims com  novos emotes e sistemas de personagens. The Sims   recebeu vários pacotes de DLC pagos desde seu lançamento. Onze pacotes de expansão, onze pacotes de jogos, dezoito pacotes de recursos e dez pacotes de ferramentas foram lançados; O pacote de expansão mais recente é o Cottage Living em 22 de julho de 2021. Várias atualizações gratuitas também foram lançadas ao longo da vida útil do jogo, incluindo os principais recursos e adições ao jogo, como grupos adicionados, personalização de personagens e ferramentas de campo", 
    "cpu": "Intel core i5", 
    "gpu": "NVIDIA GTX 650", 
    "ram": "4 GB", 
    "rom": "18 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 23,
    "Nome": "The Witcher 3 Wild Hunt GOTY", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/the-witcher-3-wild-hunt-goty-torrent.jpg", 
    "Imagem": "https://s2.glbimg.com/VFlfTKm551LqpfFf2IUFgUGlf2U=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/r/t/BEGAJcTdOS5G6VJIhkOw/2016-07-06-the-witcher-3-wild-hunt-game-of-the-year-edition-dlc.jpg", 
    "Gif": "https://media.giphy.com/media/xTk9ZvNF0KCBF9FhKM/giphy.gif", 
    "Trailer": "https://www.youtube.com/embed/qIAne6xZs6c", 
    "Download": "magnet:?xt=urn:btih:97eb2078fafd7b75717a33da5408655df83cbed9&dn=The+Witcher+3+Wild+Hunt+1.31", 
    "Descricao": "The Witcher 3: Wild Hunt é um jogo de aventura em mundo aberto ambientado em um mundo de fantasia sombrio. Você é Geralt de Rivia, contratando caçadores de monstros. Todas as ferramentas do comércio estão à sua disposição: espadas afiadas, equipamentos mortais, arcos invisíveis e poderosa magia de luta. Explore o conteúdo do seu coração antes de enfrentar o continente infestado de monstros. Seu contrato atual? Caçando o filho da profecia, uma arma viva que pode mudar a forma do mundo. A versão completa   contém todo o conteúdo para download do jogo, incluindo duas grandes expansões de história: Hearts of Stone e Blood and Wine. Esta é a oportunidade perfeita para entrar no mundo pela primeira vez ou ter uma aventura, em qualquer lugar!   Recursos:   Um enorme mundo aberto para explorar.   Visite a opulenta e corrupta cidade de Novigrad, enfrente os ventos frios que varrem as Ilhas Skellig e desafie as forças das trevas que vagam pela terra desolada e devastada. ", 
    "cpu": "Intel CPU Core i5-2500K 3.3GHz", 
    "gpu": "Nvidia GeForce GTX 660", 
    "ram": "6 GB ", 
    "rom": " 40 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 24,
    "Nome": "Horizon Zero Dawn", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/horizon-zero-dawn-torrent.jpg", 
    "Imagem": "https://files.tecnoblog.net/wp-content/uploads/2020/08/dez-dicas-para-dominar-horizon-zero-dawn005.png", 
    "Gif": "https://i.pinimg.com/originals/8d/29/1f/8d291fd7264554a051ea113af15e725d.gif", 
    "Trailer": "https://www.youtube.com/embed/9axpikOIHEo", 
    "Download": "magnet:?xt=urn:btih:2032bdc4d6e86791b0a57cad855094d97c5e1ea8&dn=Horizon+Zero+Dawn+Complete+Edition+ElAmigos", 
    "Descricao": "Orizon Zero Dawn é um emocionante jogo de RPG de ação desenvolvido exclusivamente para PlayStation   pela Guerrilla Games, criadores da popular série Killzone. Jogue como Aloy, uma caçadora habilidosa, e explore um mundo vibrante e rico cheio de misteriosas criaturas mecânicas. Embarque em uma jornada imersiva e emocional para descobrir os segredos das sociedades tribais, artefatos antigos e tecnologias avançadas que determinarão o destino deste planeta e da própria vida. Um mundo fértil após o Apocalipse: como as máquinas dominam o mundo e o que elas fazem? O que aconteceu com a civilização que viveu aqui? Explore cada canto do reino cheio de ruínas antigas e edifícios misteriosos, descubra o passado e revele os muitos segredos desta terra esquecida. Clash of Nature and Machines: Horizon Zero Dawn combina dois elementos contrastantes, reunindo um mundo vibrante cheio de beleza natural e impressionante tecnologia de ponta. Essa fusão cria uma combinação dinâmica de exploração e jogabilidade. ", 
    "cpu": "Intel Core i5-2500K@3.3GHz", 
    "gpu": "Nvidia GeForce GTX 780 (3 GB)", 
    "ram": "8 GB", 
    "rom": "60 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 25,
    "Nome": "Assassins Creed Valhalla", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/assassins-creed-valhalla-torrent.jpg", 
    "Imagem": "https://staticctf.akamaized.net/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/3JD0LQCvyzh3s2Vc2qIMfo/89f81c515c7947fb55b30731f35ca9ee/ACK_189_Season06_Niflheim_OpeningSequenceFINAL.jpg", 
    "Gif": "https://media.tenor.com/EJJs8PPj6-0AAAAd/war-izuniy.gif", 
    "Trailer": "https://www.youtube.com/embed/TUbgBVTD7VI", 
    "Download": "magnet:?xt=urn:btih:a9e52a80c37610b058d5633d05c3a0ec3253bee2&dn=Assassins+Creed+Valhalla+ElAmigos", 
    "Descricao": "A história se passa em Assassin's Creed Valhalla no final do século IX, no ano de 873, durante a invasão viking da Inglaterra. Os jogadores assumem o papel de Ivor, os vikings que, juntamente com outros clãs nórdicos, formaram o chamado Grande Exército Pagão, durante a Idade Média com Wessex, Northumbria, East Anglia e Mercia durante ataques e batalhas em Anglo -Reino saxão, governado pelo rei Alfredo. Neste ponto, Ivor encontrou o Oculto e se juntou a eles em sua batalha contra a Ordem dos Anciões.  Winchester, Londres, York e outras cidades estão incluídas no jogo para os jogadores explorarem livremente.  Partes da Noruega também estão incluídas. ", 
    "cpu": "Intel i5-4460", 
    "gpu": "NVIDIA GeForce GTX 960 (4 GB)", 
    "ram": "8 GB", 
    "rom": "60 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},
{ 
    "id": 26,
    "Nome": "eFootball PES 2021", 
    "Capa": "https://i2.wp.com/torrentjogos.net/imagem/efootball-pes-2021-torrent.jpg", 
    "Imagem": "https://www.konami.com/wepes/mobile/s/img/pes2021_ogp.png", 
    "Gif": "https://1.bp.blogspot.com/-kgsjyGtQVAA/X3O-MrWX-CI/AAAAAAAAFnM/wtdDiVBoS2Mp76291ekt6WY-dBpIaSKxACNcBGAsYHQ/s1600/comemoracao.gif", 
    "Trailer": "https://www.youtube.com/embed/GSXViWOyEO4", 
    "Download": "magnet:?xt=urn:btih:da532319adf8cd1757b65200e6b5931abfd0a4b5&dn=E.Football.PES.2021-CPY&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2980&tr=udp%3A%2F%2F9.rarbg.to%3A2860", 
    "Descricao": "A atualização da temporada do eFootball PES 2021 oferece todos os recursos populares para ganhar o título de Melhor Jogo de Esportes na E3 2019 e além!   Neste quarto de século desde o lançamento da franquia PES em 1995, convidamos você a se juntar a nós em campo para uma emocionante nova temporada de futebol.   Com os dados mais recentes de jogadores e equipas, o jogo também apresenta o modo exclusivo UEFA EURO 2020™, permitindo-te a ti e aos teus amigos simular algumas das maiores competições do desporto.", 
    "cpu": "Intel Core i5-3470", 
    "gpu": "NVIDIA GTX 670", 
    "ram": "8 GB", 
    "rom": "40 GB", 
    "Plataforma": "pc", 
    "Tipo": "jogo", 
},

      
]
            
    