const nomes = [
    {
        "nome":"Andarilho",
    },
    {
        "nome":"Penetra",
    },
    {
        "nome":"Padre", 
    },
    {
        "nome":"Cara", 
    },
    {
        "nome":"Enorme", 
    },
    {
        "nome":"Jeba", 
    },
    {
        "nome":"Jogador", 
    },
    {
        "nome":"Surfista", 
    },
    {
        "nome":"Cavaleiro", 
    },
    {
        "nome":"Senhor", 
    },
    {
        "nome":"Gentil", 
    },
    {
        "nome":"Pedro", 
    },
    {
        "nome":"Gigante", 
    },
    {
        "nome":"Anão", 
    },
    {
        "nome":"Insignificante", 
    },
    {
        "nome":"Esplêndido", 
    },
    
]

const sobrenomes = [
    {
        "sobrenome":"Errante"
    },
    {
        "sobrenome":"Comedor"
    },
    {
        "sobrenome":"Guloso"
    },
    {
        "sobrenome":"Religioso"
    },
    {
        "sobrenome":"Funkeiro"
    },
    {
        "sobrenome":"Covarde"
    },
    {
        "sobrenome":"Vascaino"
    },
    {
        "sobrenome":"Ladrão"
    },
    {
        "sobrenome":"Maluco"
    },
    {
        "sobrenome":"Fresco"
    },
    {
        "sobrenome":"Inocente"
    },
    {
        "sobrenome":"Covarde"
    },
    {
        "sobrenome":"Burro"
    },
    {
        "sobrenome":"Inteligente"
    },
    {
        "sobrenome":"Galopante"
    },
    {
        "sobrenome":"Bonito"
    },
    {
        "sobrenome":"Feio"
    },
    {
        "sobrenome":"Nerd"
    },
    {
        "sobrenome":"CDF"
    },
    {
        "sobrenome":"LOL"
    },
    {
        "sobrenome":"Familiar"
    },
    {
        "sobrenome":"Solitario"
    },
    {
        "sobrenome":"Cagado"
    },
]